development:
  adapter: postgresql
  encoding: utf8
  database: snappygram_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: utf8
  database: snappygram_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: snappygram_production
  pool: 5

cucumber:
  <<: *test